version: '3.8'
services:

  # Log aggregation service
  loki:
    container_name: loki
    restart: always
    image: grafana/loki:2.4.1
    volumes:
      - ./src/config/loki:/etc/loki
    ports:
      - "3100:3100"
    command: -config.file=./etc/loki/loki-config.yml
    networks:
      - krakura-app

  # Logging agent service
  promtail:
    container_name: promtail
    restart: always
    image: grafana/promtail:2.4.1
    volumes:
      - ./src/config/promtail:/etc/promtail
    # ports:
    #   - "1514:1514" # this is only needed if you are going to send syslogs
    command: -config.file=./etc/promtail/promtail-config.yml
    networks:
      - krakura-app
  
  # Grafana Dashboarding service
  grafana:
    container_name: grafana
    restart: always
    image: grafana/grafana-oss
    user: "501"
    volumes:
      - ./src/config/grafana/data:/var/lib/grafana
      - ./src/config/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./src/config/grafana/dashboards:/etc/grafana/provisioning/dashboards
    ports: 
      - "3000:3000"
    networks:
      - krakura-app

  # App service
  app:
    container_name: krakura
    restart: always
    image: matthewashley1/krakura:latest
    stdin_open: true
    tty: true
    init: true
    volumes:
      - ./src/config/app:/app/src/config/app
      - ./src/logs:/app/src/logs
    networks:
      - krakura-app
    depends_on:
      - loki
      - promtail
      - grafana
    entrypoint: ["node", "/app/index.js"]

# Defines seperate docker network for container services to run on 
networks:
  krakura-app:
    driver: bridge
